import { SampleDataset } from '../types';

export const SAMPLE_DATASETS: SampleDataset[] = [
  {
    id: 'hooke_law',
    title: '훅의 법칙: 추의 질량과 용수철 늘어난 길이',
    category: '물리학',
    description: '물리학 I [힘과 운동] - 추의 질량(g)을 증가시킬 때 용수철의 변형 길이(cm) 변화 관찰 데이터',
    xName: '추의 질량 (X)',
    xUnit: 'g',
    yName: '늘어난 길이 (Y)',
    yUnit: 'cm',
    defaultSlopeMeaning: '추의 질량이 1g 증가할 때마다 용수철이 늘어나는 길이(cm)를 의미합니다. 이는 용수철 상수(k)의 역수 관계와 관련이 있습니다.',
    defaultInterceptMeaning: '추를 매달지 않았을 때(0g)의 용수철의 기본 상태 변형량 또는 영점 오차를 의미합니다.',
    points: [
      { x: 0, y: 0.2, label: '0g (기본 측정)' },
      { x: 50, y: 2.5, label: '50g 추' },
      { x: 100, y: 4.9, label: '100g 추' },
      { x: 150, y: 7.4, label: '150g 추' },
      { x: 200, y: 9.8, label: '200g 추' },
      { x: 250, y: 12.3, label: '250g 추' },
      { x: 300, y: 14.7, label: '300g 추' },
    ],
  },
  {
    id: 'plant_growth',
    title: '식물 생장 관찰: 배양 일수와 줄기 길이',
    category: '생명과학',
    description: '생명과학 I [생명 활동과 에너지] - 강낭콩 싹을 틔운 후 경과 일수(일)에 따른 줄기 높이(cm) 변화',
    xName: '경과 일수 (X)',
    xUnit: '일',
    yName: '줄기 길이 (Y)',
    yUnit: 'cm',
    defaultSlopeMeaning: '하루(1일)가 지날 때마다 식물 줄기가 평균적으로 얼마나 자라는지(cm/일 생장 속도)를 나타냅니다.',
    defaultInterceptMeaning: '발아 시작 시점(0일 차)의 초기 싹의 길이 또는 측정 시작 기준값을 의미합니다.',
    points: [
      { x: 1, y: 1.2 },
      { x: 3, y: 2.8 },
      { x: 5, y: 4.5 },
      { x: 7, y: 6.3 },
      { x: 9, y: 8.0 },
      { x: 11, y: 9.9 },
      { x: 13, y: 11.6 },
      { x: 15, y: 13.4 },
    ],
  },
  {
    id: 'study_vs_score',
    title: '일주일 공부 시간과 수학 성적',
    category: '사회/경제',
    description: '확률과 통계 [통계 - 두 변수의 상관관계] - 고등학생 10명의 주간 수학 자기주도 학습 시간과 시험 성적',
    xName: '주간 공부 시간 (X)',
    xUnit: '시간',
    yName: '수학 시험 점수 (Y)',
    yUnit: '점',
    defaultSlopeMeaning: '공부 시간을 1시간 더 투자할 때 기대되는 수학 점수의 향상 폭(점수/시간)을 나타냅니다.',
    defaultInterceptMeaning: '공부를 0시간 했을 때의 기본 점수 추정치 또는 바탕 지식 점수를 의미합니다.',
    points: [
      { x: 2, y: 45, label: '학생 A' },
      { x: 4, y: 55, label: '학생 B' },
      { x: 5, y: 62, label: '학생 C' },
      { x: 7, y: 70, label: '학생 D' },
      { x: 8, y: 78, label: '학생 E' },
      { x: 10, y: 82, label: '학생 F' },
      { x: 12, y: 88, label: '학생 G' },
      { x: 14, y: 94, label: '학생 H' },
      { x: 15, y: 96, label: '학생 I' },
    ],
  },
  {
    id: 'temp_vs_icecream',
    title: '일일 최고 기온과 아이스크림 매출',
    category: '지구과학',
    description: '통합과학 / 실용수학 - 낮 최고 기온(℃)에 따른 학교 매점 아이스크림 판매량(개)',
    xName: '최고 기온 (X)',
    xUnit: '℃',
    yName: '아이스크림 판매량 (Y)',
    yUnit: '개',
    defaultSlopeMeaning: '기온이 1℃ 상승할 때 추가로 더 판매되는 아이스크림의 개수를 의미합니다.',
    defaultInterceptMeaning: '기온이 0℃일 때의 아이스크림 판매 예측량입니다. 현실적으로 추세를 확장한 수학적 모델 절편입니다.',
    points: [
      { x: 18, y: 22 },
      { x: 20, y: 35 },
      { x: 22, y: 48 },
      { x: 24, y: 62 },
      { x: 26, y: 80 },
      { x: 28, y: 95 },
      { x: 30, y: 115 },
      { x: 32, y: 132 },
      { x: 34, y: 148 },
    ],
  },
  {
    id: 'co2_vs_global_temp',
    title: '대기 중 CO₂ 농도와 지구 평균 기온 편차',
    category: '지구과학',
    description: '지구과학 I [기후 변화] - 대기 중 이산화탄소 농도(ppm) 변화에 따른 지구 온난화 기온 편차(℃)',
    xName: 'CO₂ 농도 (X)',
    xUnit: 'ppm',
    yName: '기온 편차 (Y)',
    yUnit: '℃',
    defaultSlopeMeaning: '대기 중 CO₂ 농도가 1 ppm 증가할 때마다 지구 평균 기온이 상승하는 비율(℃/ppm)입니다.',
    defaultInterceptMeaning: '기준 CO₂ 농도 대비 이상 기온 편차의 시작 기준점 수학적 모델값입니다.',
    points: [
      { x: 320, y: -0.05, label: '1965년' },
      { x: 335, y: 0.10, label: '1978년' },
      { x: 350, y: 0.28, label: '1988년' },
      { x: 370, y: 0.45, label: '2000년' },
      { x: 390, y: 0.68, label: '2010년' },
      { x: 410, y: 0.95, label: '2019년' },
      { x: 420, y: 1.15, label: '2023년' },
    ],
  },
];
